export const data_product = [
  {
    id: 1,
    name: "INISSIA",
    label: "PROMOTE",
    price: "đ4,200,000",
    old_price: "",
    image: "assets/images/product_index/img-product_1.png",
  },
  {
    id: 2,
    name: "Ispirazione Italiana Selection",
    label: "PROMOTE",
    price: "đ1,658,000",
    old_price: "",
    image: "assets/images/product_index/img-product_2.png",
  },
  {
    id: 3,
    name: "Napoli",
    label: "LIMITED",
    price: "đ15,000",
    old_price: "",
    image: "assets/images/product_index/img-product_3.png",
  },
  {
    id: 4,
    name: "Essenza Mini Black & Aeroccino 3",
    label: "ONLINE EXCLUSIVE",
    price: "đ4,200,000",
    old_price: "đ6,300,000",
    image: "assets/images/product_index/img-product_4.png",
  },
  {
    id: 5,
    name: "Essenza Mini Red & Aeroccino 3",
    label: "LIMITED",
    price: "đ4,200,000",
    old_price: "đ6,300,000",
    image: "assets/images/product_index/img-product_5.png",
  },
  {
    id: 6,
    name: "Ispirazione Italiana Intense Selection",
    label: "PROMOTE",
    price: "đ4,200,000",
    old_price: "",
    image: "assets/images/product_index/img-product_6.png",
  },
  {
    id: 7,
    name: "INISSIA",
    label: "PROMOTE",
    price: "đ4,200,000",
    old_price: "",
    image: "assets/images/product_index/img-product_1.png",
  },
  {
    id: 8,
    name: "Ispirazione Italiana Selection",
    label: "PROMOTE",
    price: "đ1,658,000",
    old_price: "",
    image: "assets/images/product_index/img-product_2.png",
  },
  {
    id: 9,
    name: "Napoli",
    label: "LIMITED",
    price: "đ15,000",
    old_price: "",
    image: "assets/images/product_index/img-product_3.png",
  },
  {
    id: 10,
    name: "Essenza Mini Black & Aeroccino 3",
    label: "ONLINE EXCLUSIVE",
    price: "đ4,200,000",
    old_price: "đ6,300,000",
    image: "assets/images/product_index/img-product_4.png",
  },
  {
    id: 11,
    name: "Essenza Mini Red & Aeroccino 3",
    label: "LIMITED",
    price: "đ4,200,000",
    old_price: "đ6,300,000",
    image: "assets/images/product_index/img-product_5.png",
  },
  {
    id: 12,
    name: "Ispirazione Italiana Intense Selection",
    label: "PROMOTE",
    price: "đ4,200,000",
    old_price: "",
    image: "assets/images/product_index/img-product_6.png",
  },
];
