export const data_product_machine = [
  {
    id: 1,
    name: "ESSENZA MINI",
    description: " Description, maximum 3 lines",
    label: "PROMOTE",
    price: "đ4,200,000",
    old_price: "",
    image: "assets/images/machines/machines_1.png",
  },
  {
    id: 2,
    name: "INISSIA",
    description: "Description, maximum 3 lines",
    label: "PROMOTE",
    price: "đ1,658,000",
    old_price: "",
    image: "assets/images/machines/machines_2.png",
  },
  {
    id: 3,
    name: "ESSENZA PLUS",
    description: "Description, maximum 3 lines",
    label: "PROMOTE",
    price: "đ15,000",
    old_price: "",
    image: "assets/images/machines/machines_3.png",
  },
  {
    id: 4,
    name: "Essenza Mini Black & Aeroccino 3",
    description: "Description, maximum 3 lines",
    label: "PROMOTE",
    price: "đ4,200,000",
    old_price: "đ6,300,000",
    image: "assets/images/machines/machines_4.png",
  },
  {
    id: 5,
    name: "Essenza Mini Black & Aeroccino 3",
    description: "Description, maximum 3 lines",
    label: "ONLINE EXCLUSUVE",
    price: "đ4,200,000",
    old_price: "đ6,300,000",
    image: "assets/images/machines/machines_5.png",
  },
  {
    id: 6,
    name: "ESSENZA MINI WHITE & AEROCCINO 3",
    description: "Description, maximum 3 lines",
    label: "PROMOTE",
    price: "đ4,200,000",
    old_price: "",
    image: "assets/images/machines/machines_6.png",
  },
  {
    id: 7,
    name: "Inissia Black & Aeroccino 3",
    description: "Description, maximum 3 lines",
    label: "PROMOTE",
    price: "đ4,200,000",
    old_price: "",
    image: "assets/images/machines/machines_7.png",
  },
  {
    id: 8,
    name: "Inissia Black & Aeroccino 3",
    description: "Description, maximum 3 lines",
    label: "PROMOTE",
    price: "đ1,658,000",
    old_price: "",
    image: "assets/images/machines/machines_8.png",
  },
  {
    id: 9,
    name: "Inissia Red & Aeroccino 3",
    description: "Description, maximum 3 lines",
    label: "LIMITED",
    price: "đ15,000",
    old_price: "",
    image: "assets/images/machines/machines_9.png",
  },
  {
    id: 10,
    name: "Pixie Red & Aeroccino 3",
    description: "Description, maximum 3 lines",
    label: "PROMOTE",
    price: "đ4,200,000",
    old_price: "đ6,300,000",
    image: "assets/images/machines/machines_10.png",
  },
  {
    id: 11,
    name: "Pixie Titan & Aeroccino 3",
    description: "Description, maximum 3 lines",
    label: "LIMITED",
    price: "đ4,200,000",
    old_price: "đ6,300,000",
    image: "assets/images/machines/machines_11.png",
  },
  {
    id: 12,
    name: "LATTISSIMA ONE",
    description: "Description, maximum 3 lines",
    label: "PROMOTE",
    price: "đ4,200,000",
    old_price: "",
    image: "assets/images/machines/machines_12.png",
  },
  {
    id: 12,
    name: "GRAN LATTISSIMA",
    description: "Description, maximum 3 lines",
    label: "PROMOTE",
    price: "đ4,200,000",
    old_price: "",
    image: "assets/images/machines/machines_13.png",
  },
];
